# Generated by Django 3.2.3 on 2021-06-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessagingApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Readed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
